In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from IPython.display import display
import datetime

matches_table = pd.read_csv('data/matches.csv')
display(matches_table)

,Date,Match Number,Stage,Player 1,Player 2,Score 1,Score 2
0,2023-11-18,1,Group,Evan Sooklal,Will Simpson,2,6
1,2023-11-18,2,Group,Paul Bartenfeld,Roman Ramirez,2,6
2,2023-11-18,3,Group,Roman Ramirez,Evan Sooklal,6,3
3,2023-11-18,4,Group,Will Simpson,Paul Bartenfeld,6,1
4,2023-11-18,5,Group,Paul Bartenfeld,Evan Sooklal,1,6
5,2023-11-18,6,Group,Will Simpson,Roman Ramirez,3,6
6,2023-11-18,7,Group,Will Simpson,Evan Sooklal,6,2
7,2023-11-18,8,Group,Roman Ramirez,Paul Bartenfeld,6,4
8,2023-11-18,9,Group,Evan Sooklal,Roman Ramirez,6,5
9,2023-11-18,10,Group,Paul Bartenfeld,Will Simpson,4,6
10,2023-11-18,11,Group,Evan Sooklal,Paul Bartenfeld,6,5
11,2023-11-18,12,Group,Roman Ramirez,Will Simpson,6,2
12,2023-11-18,1,Final,Roman Ramirez,Will Simpson,2,6
13,2023-11-18,2,Final,Will Simpson,Roman Ramirez,4,6
14,2023-11-18,3,Final,Roman Ramirez,Will Simpson,6,4
15,2023-12-02,1,Group,Roman Ramirez,Aaron Carter,4,6
16,2023-12-02,2,Group,Will Simpson,Paul Bartenfeld,6,4
17,2023-12-02,3,Group,Aaron Carter,Will Simpson,4,6
18,2023-12-02,4,Group,Evan Sooklal,Roman Ramirez,6,2
19,2023-12-02,5,Group,Will Simpson,Evan Sooklal,6,2
20,2023-12-02,6,Group,Paul Bartenfeld,Aaron Carter,6,3
21,2023-12-02,7,Group,Evan Sooklal,Paul Bartenfeld,6,4
22,2023-12-02,8,Group,Roman Ramirez,Will Simpson,6,4
23,2023-12-02,9,Group,Paul Bartenfeld,Roman Ramirez,6,3
24,2023-12-02,10,Group,Aaron Carter,Evan Sooklal,6,3
25,2023-12-02,11,Group,Aaron Carter,Roman Ramirez,0,6
26,2023-12-02,12,Group,Paul Bartenfeld,Will Simpson,1,6
27,2023-12-02,13,Group,Will Simpson,Aaron Carter,3,6
28,2023-12-02,14,Group,Roman Ramirez,Evan Sooklal,2,6
29,2023-12-02,15,Group,Evan Sooklal,Will Simpson,5,6
30,2023-12-02,16,Group,Aaron Carter,Paul Bartenfeld,6,3
31,2023-12-02,17,Group,Paul Bartenfeld,Evan Sooklal,6,5
32,2023-12-02,18,Group,Will Simpson,Roman Ramirez,6,5
33,2023-12-02,19,Group,Roman Ramirez,Paul Bartenfeld,4,6
34,2023-12-02,20,Group,Evan Sooklal,Aaron Carter,6,4
35,2023-12-02,1,Final,Will Simpson,Evan Sooklal,6,2
36,2023-12-02,2,Final,Will Simpson,Evan Sooklal,6,1

In [3]:
set_players = sorted(set(matches_table['Player 1']).union(matches_table['Player 2']))
display(set_players)

['Aaron Carter',
 'Evan Sooklal',
 'Paul Bartenfeld',
 'Roman Ramirez',
 'Will Simpson']

In [11]:
spread_table = pd.DataFrame(np.zeros([5, 5]))
spread_table.replace(0, np.NaN, inplace=True)
spread_table.index = set_players
spread_table.columns = set_players

for (i, row) in matches_table.iterrows():
    (p1, p2) = sorted([row['Player 1'], row['Player 2']])
    spread_table.loc[p1, p2] = row['Score 1'] - row['Score 2']

display(spread_table)

,Aaron Carter,Evan Sooklal,Paul Bartenfeld,Roman Ramirez,Will Simpson
Aaron Carter,NaN,3.0,3.0,-6.0,-2.0
Evan Sooklal,2.0,NaN,2.0,4.0,-1.0
Paul Bartenfeld,3.0,1.0,NaN,3.0,-5.0
Roman Ramirez,-2.0,-4.0,-2.0,NaN,2.0
Will Simpson,-3.0,5.0,2.0,1.0,NaN

In [35]:
ppg_table = pd.DataFrame()
ppg_table.index = set_players
ppg_table['Points For'] = 0
ppg_table['Points Against'] = 0
ppg_table['Point Difference'] = 0
ppg_table['Games Played'] = 0

for (i, row) in matches_table.iterrows():
    ppg_table.loc[row['Player 1'], 'Points For'] += row['Score 1']
    ppg_table.loc[row['Player 1'], 'Points Against'] += row['Score 2']
    ppg_table.loc[row['Player 2'], 'Points For'] += row['Score 2']
    ppg_table.loc[row['Player 2'], 'Points Against'] += row['Score 1']
    ppg_table.loc[row['Player 1'], 'Games Played'] += 1
    ppg_table.loc[row['Player 2'], 'Games Played'] += 1
    ppg_table['Point Difference'] = ppg_table['Points For'] - ppg_table['Points Against']

ppg_table['PPG'] = ppg_table['Point Difference'] / ppg_table['Games Played']

display(ppg_table)

,Points For,Points Against,Point Difference,Games Played,PPG
Aaron Carter,35,37,-2,8,-0.250000
Evan Sooklal,67,77,-10,16,-0.625000
Paul Bartenfeld,53,75,-22,14,-1.571429
Roman Ramirez,81,74,7,17,0.411765
Will Simpson,98,71,27,19,1.421053

In [4]:


fig = sns.heatmap()
fig.show()

TypeError: heatmap() missing 1 required positional argument: 'data'